# Generated by Django 5.2.5 on 2025-08-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('dueno', models.CharField(max_length=100)),
            ],
        ),
    ]
